# Sample Data


commitments = [
    {
        "id": 1,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 15000000,
        "currency": "GBP",
    },
    {
        "id": 2,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 31000000,
        "currency": "GBP",
    },
    {
        "id": 3,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 58000000,
        "currency": "GBP",
    },
    {
        "id": 4,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 72000000,
        "currency": "GBP",
    },
    {
        "id": 5,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 1000000,
        "currency": "GBP",
    },
    {
        "id": 6,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 17000000,
        "currency": "GBP",
    },
    {
        "id": 7,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 83000000,
        "currency": "GBP",
    },
    {
        "id": 8,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 28000000,
        "currency": "GBP",
    },
    {
        "id": 9,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 85000000,
        "currency": "GBP",
    },
    {
        "id": 10,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 31000000,
        "currency": "GBP",
    },
    {
        "id": 11,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 45000000,
        "currency": "GBP",
    },
    {
        "id": 12,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 48000000,
        "currency": "GBP",
    },
    {
        "id": 13,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 45000000,
        "currency": "GBP",
    },
    {
        "id": 14,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 12000000,
        "currency": "GBP",
    },
    {
        "id": 15,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 30000000,
        "currency": "GBP",
    },
    {
        "id": 16,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 94000000,
        "currency": "GBP",
    },
    {
        "id": 17,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 17000000,
        "currency": "GBP",
    },
    {
        "id": 18,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 86000000,
        "currency": "GBP",
    },
    {
        "id": 19,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 32000000,
        "currency": "GBP",
    },
    {
        "id": 20,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 38000000,
        "currency": "GBP",
    },
    {
        "id": 21,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 6000000,
        "currency": "GBP",
    },
    {
        "id": 22,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 61000000,
        "currency": "GBP",
    },
    {
        "id": 23,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 63000000,
        "currency": "GBP",
    },
    {
        "id": 24,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 15000000,
        "currency": "GBP",
    },
    {
        "id": 25,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 70000000,
        "currency": "GBP",
    },
    {
        "id": 26,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 27000000,
        "currency": "GBP",
    },
    {
        "id": 27,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 51000000,
        "currency": "GBP",
    },
    {
        "id": 28,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 92000000,
        "currency": "GBP",
    },
    {
        "id": 29,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 10000000,
        "currency": "GBP",
    },
    {
        "id": 30,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 41000000,
        "currency": "GBP",
    },
    {
        "id": 31,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 69000000,
        "currency": "GBP",
    },
    {
        "id": 32,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 66000000,
        "currency": "GBP",
    },
    {
        "id": 33,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 75000000,
        "currency": "GBP",
    },
    {
        "id": 34,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 74000000,
        "currency": "GBP",
    },
    {
        "id": 35,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 86000000,
        "currency": "GBP",
    },
    {
        "id": 36,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 36000000,
        "currency": "GBP",
    },
    {
        "id": 37,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 55000000,
        "currency": "GBP",
    },
    {
        "id": 38,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 60000000,
        "currency": "GBP",
    },
    {
        "id": 39,
        "investor_id": 1,
        "asset_class_id": 6,
        "amount": 4000000,
        "currency": "GBP",
    },
    {
        "id": 40,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 75000000,
        "currency": "GBP",
    },
    {
        "id": 41,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 86000000,
        "currency": "GBP",
    },
    {
        "id": 42,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 63000000,
        "currency": "GBP",
    },
    {
        "id": 43,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 4000000,
        "currency": "GBP",
    },
    {
        "id": 44,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 82000000,
        "currency": "GBP",
    },
    {
        "id": 45,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 87000000,
        "currency": "GBP",
    },
    {
        "id": 46,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 11000000,
        "currency": "GBP",
    },
    {
        "id": 47,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 89000000,
        "currency": "GBP",
    },
    {
        "id": 48,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 12000000,
        "currency": "GBP",
    },
    {
        "id": 49,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 22000000,
        "currency": "GBP",
    },
    {
        "id": 50,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 16000000,
        "currency": "GBP",
    },
    {
        "id": 51,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 24000000,
        "currency": "GBP",
    },
    {
        "id": 52,
        "investor_id": 3,
        "asset_class_id": 1,
        "amount": 40000000,
        "currency": "GBP",
    },
    {
        "id": 53,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 15000000,
        "currency": "GBP",
    },
    {
        "id": 54,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 45000000,
        "currency": "GBP",
    },
    {
        "id": 55,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 36000000,
        "currency": "GBP",
    },
    {
        "id": 56,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 78000000,
        "currency": "GBP",
    },
    {
        "id": 57,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 69000000,
        "currency": "GBP",
    },
    {
        "id": 58,
        "investor_id": 3,
        "asset_class_id": 5,
        "amount": 65000000,
        "currency": "GBP",
    },
    {
        "id": 59,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 70000000,
        "currency": "GBP",
    },
    {
        "id": 60,
        "investor_id": 3,
        "asset_class_id": 4,
        "amount": 11000000,
        "currency": "GBP",
    },
    {
        "id": 61,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 87000000,
        "currency": "GBP",
    },
    {
        "id": 62,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 5000000,
        "currency": "GBP",
    },
    {
        "id": 63,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 18000000,
        "currency": "GBP",
    },
    {
        "id": 64,
        "investor_id": 3,
        "asset_class_id": 4,
        "amount": 69000000,
        "currency": "GBP",
    },
    {
        "id": 65,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 15000000,
        "currency": "GBP",
    },
    {
        "id": 66,
        "investor_id": 1,
        "asset_class_id": 6,
        "amount": 76000000,
        "currency": "GBP",
    },
    {
        "id": 67,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 31000000,
        "currency": "GBP",
    },
    {
        "id": 68,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 44000000,
        "currency": "GBP",
    },
    {
        "id": 69,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 8000000,
        "currency": "GBP",
    },
    {
        "id": 70,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 32000000,
        "currency": "GBP",
    },
    {
        "id": 71,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 62000000,
        "currency": "GBP",
    },
    {
        "id": 72,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 36000000,
        "currency": "GBP",
    },
    {
        "id": 73,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 88000000,
        "currency": "GBP",
    },
    {
        "id": 74,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 30000000,
        "currency": "GBP",
    },
    {
        "id": 75,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 4000000,
        "currency": "GBP",
    },
    {
        "id": 76,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 59000000,
        "currency": "GBP",
    },
    {
        "id": 77,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 79000000,
        "currency": "GBP",
    },
    {
        "id": 78,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 71000000,
        "currency": "GBP",
    },
    {
        "id": 79,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 16000000,
        "currency": "GBP",
    },
    {
        "id": 80,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 14000000,
        "currency": "GBP",
    },
    {
        "id": 81,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 58000000,
        "currency": "GBP",
    },
    {
        "id": 82,
        "investor_id": 3,
        "asset_class_id": 1,
        "amount": 92000000,
        "currency": "GBP",
    },
    {
        "id": 83,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 47000000,
        "currency": "GBP",
    },
    {
        "id": 84,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 94000000,
        "currency": "GBP",
    },
    {
        "id": 85,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 18000000,
        "currency": "GBP",
    },
    {
        "id": 86,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 49000000,
        "currency": "GBP",
    },
    {
        "id": 87,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 40000000,
        "currency": "GBP",
    },
    {
        "id": 88,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 96000000,
        "currency": "GBP",
    },
    {
        "id": 89,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 35000000,
        "currency": "GBP",
    },
    {
        "id": 90,
        "investor_id": 3,
        "asset_class_id": 6,
        "amount": 69000000,
        "currency": "GBP",
    },
    {
        "id": 91,
        "investor_id": 3,
        "asset_class_id": 4,
        "amount": 53000000,
        "currency": "GBP",
    },
    {
        "id": 92,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 14000000,
        "currency": "GBP",
    },
    {
        "id": 93,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 31000000,
        "currency": "GBP",
    },
    {
        "id": 94,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 63000000,
        "currency": "GBP",
    },
    {
        "id": 95,
        "investor_id": 3,
        "asset_class_id": 4,
        "amount": 55000000,
        "currency": "GBP",
    },
    {
        "id": 96,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 60000000,
        "currency": "GBP",
    },
    {
        "id": 97,
        "investor_id": 3,
        "asset_class_id": 4,
        "amount": 55000000,
        "currency": "GBP",
    },
    {
        "id": 98,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 66000000,
        "currency": "GBP",
    },
    {
        "id": 99,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 65000000,
        "currency": "GBP",
    },
    {
        "id": 100,
        "investor_id": 3,
        "asset_class_id": 4,
        "amount": 54000000,
        "currency": "GBP",
    },
    {
        "id": 101,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 78000000,
        "currency": "GBP",
    },
    {
        "id": 102,
        "investor_id": 3,
        "asset_class_id": 6,
        "amount": 73000000,
        "currency": "GBP",
    },
    {
        "id": 103,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 7000000,
        "currency": "GBP",
    },
    {
        "id": 104,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 95000000,
        "currency": "GBP",
    },
    {
        "id": 105,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 54000000,
        "currency": "GBP",
    },
    {
        "id": 106,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 75000000,
        "currency": "GBP",
    },
    {
        "id": 107,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 89000000,
        "currency": "GBP",
    },
    {
        "id": 108,
        "investor_id": 3,
        "asset_class_id": 1,
        "amount": 39000000,
        "currency": "GBP",
    },
    {
        "id": 109,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 32000000,
        "currency": "GBP",
    },
    {
        "id": 110,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 10000000,
        "currency": "GBP",
    },
    {
        "id": 111,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 91000000,
        "currency": "GBP",
    },
    {
        "id": 112,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 36000000,
        "currency": "GBP",
    },
    {
        "id": 113,
        "investor_id": 3,
        "asset_class_id": 4,
        "amount": 7000000,
        "currency": "GBP",
    },
    {
        "id": 114,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 37000000,
        "currency": "GBP",
    },
    {
        "id": 115,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 37000000,
        "currency": "GBP",
    },
    {
        "id": 116,
        "investor_id": 3,
        "asset_class_id": 6,
        "amount": 52000000,
        "currency": "GBP",
    },
    {
        "id": 117,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 89000000,
        "currency": "GBP",
    },
    {
        "id": 118,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 80000000,
        "currency": "GBP",
    },
    {
        "id": 119,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 67000000,
        "currency": "GBP",
    },
    {
        "id": 120,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 54000000,
        "currency": "GBP",
    },
    {
        "id": 121,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 96000000,
        "currency": "GBP",
    },
    {
        "id": 122,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 18000000,
        "currency": "GBP",
    },
    {
        "id": 123,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 47000000,
        "currency": "GBP",
    },
    {
        "id": 124,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 72000000,
        "currency": "GBP",
    },
    {
        "id": 125,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 31000000,
        "currency": "GBP",
    },
    {
        "id": 126,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 93000000,
        "currency": "GBP",
    },
    {
        "id": 127,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 77000000,
        "currency": "GBP",
    },
    {
        "id": 128,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 4000000,
        "currency": "GBP",
    },
    {
        "id": 129,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 76000000,
        "currency": "GBP",
    },
    {
        "id": 130,
        "investor_id": 1,
        "asset_class_id": 6,
        "amount": 92000000,
        "currency": "GBP",
    },
    {
        "id": 131,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 4000000,
        "currency": "GBP",
    },
    {
        "id": 132,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 17000000,
        "currency": "GBP",
    },
    {
        "id": 133,
        "investor_id": 1,
        "asset_class_id": 6,
        "amount": 20000000,
        "currency": "GBP",
    },
    {
        "id": 134,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 81000000,
        "currency": "GBP",
    },
    {
        "id": 135,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 51000000,
        "currency": "GBP",
    },
    {
        "id": 136,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 53000000,
        "currency": "GBP",
    },
    {
        "id": 137,
        "investor_id": 1,
        "asset_class_id": 6,
        "amount": 60000000,
        "currency": "GBP",
    },
    {
        "id": 138,
        "investor_id": 3,
        "asset_class_id": 5,
        "amount": 89000000,
        "currency": "GBP",
    },
    {
        "id": 139,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 81000000,
        "currency": "GBP",
    },
    {
        "id": 140,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 22000000,
        "currency": "GBP",
    },
    {
        "id": 141,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 31000000,
        "currency": "GBP",
    },
    {
        "id": 142,
        "investor_id": 3,
        "asset_class_id": 6,
        "amount": 51000000,
        "currency": "GBP",
    },
    {
        "id": 143,
        "investor_id": 3,
        "asset_class_id": 5,
        "amount": 55000000,
        "currency": "GBP",
    },
    {
        "id": 144,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 27000000,
        "currency": "GBP",
    },
    {
        "id": 145,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 67000000,
        "currency": "GBP",
    },
    {
        "id": 146,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 3000000,
        "currency": "GBP",
    },
    {
        "id": 147,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 22000000,
        "currency": "GBP",
    },
    {
        "id": 148,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 94000000,
        "currency": "GBP",
    },
    {
        "id": 149,
        "investor_id": 3,
        "asset_class_id": 6,
        "amount": 8000000,
        "currency": "GBP",
    },
    {
        "id": 150,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 4000000,
        "currency": "GBP",
    },
    {
        "id": 151,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 92000000,
        "currency": "GBP",
    },
    {
        "id": 152,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 75000000,
        "currency": "GBP",
    },
    {
        "id": 153,
        "investor_id": 3,
        "asset_class_id": 1,
        "amount": 69000000,
        "currency": "GBP",
    },
    {
        "id": 154,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 21000000,
        "currency": "GBP",
    },
    {
        "id": 155,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 1000000,
        "currency": "GBP",
    },
    {
        "id": 156,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 28000000,
        "currency": "GBP",
    },
    {
        "id": 157,
        "investor_id": 2,
        "asset_class_id": 2,
        "amount": 41000000,
        "currency": "GBP",
    },
    {
        "id": 158,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 63000000,
        "currency": "GBP",
    },
    {
        "id": 159,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 55000000,
        "currency": "GBP",
    },
    {
        "id": 160,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 94000000,
        "currency": "GBP",
    },
    {
        "id": 161,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 42000000,
        "currency": "GBP",
    },
    {
        "id": 162,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 40000000,
        "currency": "GBP",
    },
    {
        "id": 163,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 68000000,
        "currency": "GBP",
    },
    {
        "id": 164,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 45000000,
        "currency": "GBP",
    },
    {
        "id": 165,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 25000000,
        "currency": "GBP",
    },
    {
        "id": 166,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 39000000,
        "currency": "GBP",
    },
    {
        "id": 167,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 80000000,
        "currency": "GBP",
    },
    {
        "id": 168,
        "investor_id": 1,
        "asset_class_id": 6,
        "amount": 70000000,
        "currency": "GBP",
    },
    {
        "id": 169,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 52000000,
        "currency": "GBP",
    },
    {
        "id": 170,
        "investor_id": 3,
        "asset_class_id": 6,
        "amount": 45000000,
        "currency": "GBP",
    },
    {
        "id": 171,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 81000000,
        "currency": "GBP",
    },
    {
        "id": 172,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 9000000,
        "currency": "GBP",
    },
    {
        "id": 173,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 59000000,
        "currency": "GBP",
    },
    {
        "id": 174,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 55000000,
        "currency": "GBP",
    },
    {
        "id": 175,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 3000000,
        "currency": "GBP",
    },
    {
        "id": 176,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 97000000,
        "currency": "GBP",
    },
    {
        "id": 177,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 1000000,
        "currency": "GBP",
    },
    {
        "id": 178,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 20000000,
        "currency": "GBP",
    },
    {
        "id": 179,
        "investor_id": 3,
        "asset_class_id": 1,
        "amount": 12000000,
        "currency": "GBP",
    },
    {
        "id": 180,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 36000000,
        "currency": "GBP",
    },
    {
        "id": 181,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 12000000,
        "currency": "GBP",
    },
    {
        "id": 182,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 42000000,
        "currency": "GBP",
    },
    {
        "id": 183,
        "investor_id": 3,
        "asset_class_id": 4,
        "amount": 47000000,
        "currency": "GBP",
    },
    {
        "id": 184,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 32000000,
        "currency": "GBP",
    },
    {
        "id": 185,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 5000000,
        "currency": "GBP",
    },
    {
        "id": 186,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 18000000,
        "currency": "GBP",
    },
    {
        "id": 187,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 59000000,
        "currency": "GBP",
    },
    {
        "id": 188,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 34000000,
        "currency": "GBP",
    },
    {
        "id": 189,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 61000000,
        "currency": "GBP",
    },
    {
        "id": 190,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 4000000,
        "currency": "GBP",
    },
    {
        "id": 191,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 22000000,
        "currency": "GBP",
    },
    {
        "id": 192,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 52000000,
        "currency": "GBP",
    },
    {
        "id": 193,
        "investor_id": 3,
        "asset_class_id": 5,
        "amount": 69000000,
        "currency": "GBP",
    },
    {
        "id": 194,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 76000000,
        "currency": "GBP",
    },
    {
        "id": 195,
        "investor_id": 3,
        "asset_class_id": 6,
        "amount": 18000000,
        "currency": "GBP",
    },
    {
        "id": 196,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 49000000,
        "currency": "GBP",
    },
    {
        "id": 197,
        "investor_id": 3,
        "asset_class_id": 6,
        "amount": 5000000,
        "currency": "GBP",
    },
    {
        "id": 198,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 73000000,
        "currency": "GBP",
    },
    {
        "id": 199,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 18000000,
        "currency": "GBP",
    },
    {
        "id": 200,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 90000000,
        "currency": "GBP",
    },
    {
        "id": 201,
        "investor_id": 1,
        "asset_class_id": 6,
        "amount": 92000000,
        "currency": "GBP",
    },
    {
        "id": 202,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 23000000,
        "currency": "GBP",
    },
    {
        "id": 203,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 1000000,
        "currency": "GBP",
    },
    {
        "id": 204,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 94000000,
        "currency": "GBP",
    },
    {
        "id": 205,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 43000000,
        "currency": "GBP",
    },
    {
        "id": 206,
        "investor_id": 3,
        "asset_class_id": 1,
        "amount": 36000000,
        "currency": "GBP",
    },
    {
        "id": 207,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 56000000,
        "currency": "GBP",
    },
    {
        "id": 208,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 24000000,
        "currency": "GBP",
    },
    {
        "id": 209,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 86000000,
        "currency": "GBP",
    },
    {
        "id": 210,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 19000000,
        "currency": "GBP",
    },
    {
        "id": 211,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 28000000,
        "currency": "GBP",
    },
    {
        "id": 212,
        "investor_id": 3,
        "asset_class_id": 1,
        "amount": 41000000,
        "currency": "GBP",
    },
    {
        "id": 213,
        "investor_id": 3,
        "asset_class_id": 6,
        "amount": 19000000,
        "currency": "GBP",
    },
    {
        "id": 214,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 63000000,
        "currency": "GBP",
    },
    {
        "id": 215,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 98000000,
        "currency": "GBP",
    },
    {
        "id": 216,
        "investor_id": 3,
        "asset_class_id": 5,
        "amount": 69000000,
        "currency": "GBP",
    },
    {
        "id": 217,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 26000000,
        "currency": "GBP",
    },
    {
        "id": 218,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 38000000,
        "currency": "GBP",
    },
    {
        "id": 219,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 69000000,
        "currency": "GBP",
    },
    {
        "id": 220,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 57000000,
        "currency": "GBP",
    },
    {
        "id": 221,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 87000000,
        "currency": "GBP",
    },
    {
        "id": 222,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 36000000,
        "currency": "GBP",
    },
    {
        "id": 223,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 77000000,
        "currency": "GBP",
    },
    {
        "id": 224,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 50000000,
        "currency": "GBP",
    },
    {
        "id": 225,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 9000000,
        "currency": "GBP",
    },
    {
        "id": 226,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 13000000,
        "currency": "GBP",
    },
    {
        "id": 227,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 19000000,
        "currency": "GBP",
    },
    {
        "id": 228,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 93000000,
        "currency": "GBP",
    },
    {
        "id": 229,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 82000000,
        "currency": "GBP",
    },
    {
        "id": 230,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 53000000,
        "currency": "GBP",
    },
    {
        "id": 231,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 54000000,
        "currency": "GBP",
    },
    {
        "id": 232,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 69000000,
        "currency": "GBP",
    },
    {
        "id": 233,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 42000000,
        "currency": "GBP",
    },
    {
        "id": 234,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 10000000,
        "currency": "GBP",
    },
    {
        "id": 235,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 93000000,
        "currency": "GBP",
    },
    {
        "id": 236,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 95000000,
        "currency": "GBP",
    },
    {
        "id": 237,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 10000000,
        "currency": "GBP",
    },
    {
        "id": 238,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 9000000,
        "currency": "GBP",
    },
    {
        "id": 239,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 60000000,
        "currency": "GBP",
    },
    {
        "id": 240,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 30000000,
        "currency": "GBP",
    },
    {
        "id": 241,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 42000000,
        "currency": "GBP",
    },
    {
        "id": 242,
        "investor_id": 3,
        "asset_class_id": 4,
        "amount": 11000000,
        "currency": "GBP",
    },
    {
        "id": 243,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 96000000,
        "currency": "GBP",
    },
    {
        "id": 244,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 50000000,
        "currency": "GBP",
    },
    {
        "id": 245,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 32000000,
        "currency": "GBP",
    },
    {
        "id": 246,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 79000000,
        "currency": "GBP",
    },
    {
        "id": 247,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 31000000,
        "currency": "GBP",
    },
    {
        "id": 248,
        "investor_id": 3,
        "asset_class_id": 5,
        "amount": 9000000,
        "currency": "GBP",
    },
    {
        "id": 249,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 24000000,
        "currency": "GBP",
    },
    {
        "id": 250,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 38000000,
        "currency": "GBP",
    },
    {
        "id": 251,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 83000000,
        "currency": "GBP",
    },
    {
        "id": 252,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 72000000,
        "currency": "GBP",
    },
    {
        "id": 253,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 17000000,
        "currency": "GBP",
    },
    {
        "id": 254,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 50000000,
        "currency": "GBP",
    },
    {
        "id": 255,
        "investor_id": 1,
        "asset_class_id": 6,
        "amount": 39000000,
        "currency": "GBP",
    },
    {
        "id": 256,
        "investor_id": 3,
        "asset_class_id": 4,
        "amount": 60000000,
        "currency": "GBP",
    },
    {
        "id": 257,
        "investor_id": 1,
        "asset_class_id": 5,
        "amount": 7000000,
        "currency": "GBP",
    },
    {
        "id": 258,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 5000000,
        "currency": "GBP",
    },
    {
        "id": 259,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 69000000,
        "currency": "GBP",
    },
    {
        "id": 260,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 17000000,
        "currency": "GBP",
    },
    {
        "id": 261,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 95000000,
        "currency": "GBP",
    },
    {
        "id": 262,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 21000000,
        "currency": "GBP",
    },
    {
        "id": 263,
        "investor_id": 3,
        "asset_class_id": 2,
        "amount": 48000000,
        "currency": "GBP",
    },
    {
        "id": 264,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 95000000,
        "currency": "GBP",
    },
    {
        "id": 265,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 89000000,
        "currency": "GBP",
    },
    {
        "id": 266,
        "investor_id": 1,
        "asset_class_id": 4,
        "amount": 1000000,
        "currency": "GBP",
    },
    {
        "id": 267,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 48000000,
        "currency": "GBP",
    },
    {
        "id": 268,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 42000000,
        "currency": "GBP",
    },
    {
        "id": 269,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 5000000,
        "currency": "GBP",
    },
    {
        "id": 270,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 17000000,
        "currency": "GBP",
    },
    {
        "id": 271,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 42000000,
        "currency": "GBP",
    },
    {
        "id": 272,
        "investor_id": 1,
        "asset_class_id": 3,
        "amount": 6000000,
        "currency": "GBP",
    },
    {
        "id": 273,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 6000000,
        "currency": "GBP",
    },
    {
        "id": 274,
        "investor_id": 4,
        "asset_class_id": 5,
        "amount": 17000000,
        "currency": "GBP",
    },
    {
        "id": 275,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 73000000,
        "currency": "GBP",
    },
    {
        "id": 276,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 64000000,
        "currency": "GBP",
    },
    {
        "id": 277,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 0,
        "currency": "GBP",
    },
    {
        "id": 278,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 89000000,
        "currency": "GBP",
    },
    {
        "id": 279,
        "investor_id": 3,
        "asset_class_id": 5,
        "amount": 21000000,
        "currency": "GBP",
    },
    {
        "id": 280,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 12000000,
        "currency": "GBP",
    },
    {
        "id": 281,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 31000000,
        "currency": "GBP",
    },
    {
        "id": 282,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 46000000,
        "currency": "GBP",
    },
    {
        "id": 283,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 68000000,
        "currency": "GBP",
    },
    {
        "id": 284,
        "investor_id": 2,
        "asset_class_id": 3,
        "amount": 16000000,
        "currency": "GBP",
    },
    {
        "id": 285,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 29000000,
        "currency": "GBP",
    },
    {
        "id": 286,
        "investor_id": 1,
        "asset_class_id": 1,
        "amount": 26000000,
        "currency": "GBP",
    },
    {
        "id": 287,
        "investor_id": 4,
        "asset_class_id": 1,
        "amount": 8000000,
        "currency": "GBP",
    },
    {
        "id": 288,
        "investor_id": 1,
        "asset_class_id": 2,
        "amount": 45000000,
        "currency": "GBP",
    },
    {
        "id": 289,
        "investor_id": 2,
        "asset_class_id": 1,
        "amount": 63000000,
        "currency": "GBP",
    },
    {
        "id": 290,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 44000000,
        "currency": "GBP",
    },
    {
        "id": 291,
        "investor_id": 2,
        "asset_class_id": 4,
        "amount": 20000000,
        "currency": "GBP",
    },
    {
        "id": 292,
        "investor_id": 4,
        "asset_class_id": 2,
        "amount": 84000000,
        "currency": "GBP",
    },
    {
        "id": 293,
        "investor_id": 4,
        "asset_class_id": 6,
        "amount": 55000000,
        "currency": "GBP",
    },
    {
        "id": 294,
        "investor_id": 4,
        "asset_class_id": 3,
        "amount": 68000000,
        "currency": "GBP",
    },
    {
        "id": 295,
        "investor_id": 3,
        "asset_class_id": 6,
        "amount": 20000000,
        "currency": "GBP",
    },
    {
        "id": 296,
        "investor_id": 2,
        "asset_class_id": 6,
        "amount": 57000000,
        "currency": "GBP",
    },
    {
        "id": 297,
        "investor_id": 2,
        "asset_class_id": 5,
        "amount": 37000000,
        "currency": "GBP",
    },
    {
        "id": 298,
        "investor_id": 4,
        "asset_class_id": 4,
        "amount": 13000000,
        "currency": "GBP",
    },
    {
        "id": 299,
        "investor_id": 3,
        "asset_class_id": 5,
        "amount": 37000000,
        "currency": "GBP",
    },
    {
        "id": 300,
        "investor_id": 3,
        "asset_class_id": 3,
        "amount": 34000000,
        "currency": "GBP",
    },
]

asset_classes = [
    {"id": 1, "name": "Infrastructure"},
    {"id": 2, "name": "Hedge Funds"},
    {"id": 3, "name": "Private Equity"},
    {"id": 4, "name": "Natural Resources"},
    {"id": 5, "name": "Real Estate"},
    {"id": 6, "name": "Private Debt"},
]
